### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by crouti** [doctolib/code-of-conduct#1]
Bonjour,

Nous voudrions nous connecter à l'API Doctolib pour envoyer / recevoir des données patients.
Ou puis-je trouver de la documentation sur votre API ?

Merci!

**Comment by bankair** [comment]
Bonjour,

Je crains que ce projet github n'ai rien à voir avec les infrastructures techniques de Doctolib. Je ferme donc cette issue.

Désolé de ne pas pouvoir vous aider.

Bonne journée.

**Comment by crouti** [comment]
Ok merci, pas de contact à me proposer ?
